/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package penjualan.view;

import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import static penjualan.Penjualan.SESSION_FACTORY;
import penjualan.model.Pelanggan;
import penjualan.model.PelangganTableModel;
import sun.security.pkcs11.wrapper.Functions;

/**
 *
 * @author STMIK-I-17
 */
public class ListPelanggan extends javax.swing.JDialog {

    /**
     * Creates new form ListPelanggan
     */
    private Session session;
    private Pelanggan pelanggan;
    public ListPelanggan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pelanggan = new Pelanggan();
        showData();
    }
    
    public void showData(){
        try{
            session = SESSION_FACTORY.openSession();
            session.beginTransaction();
            List<Pelanggan> pelanggans=session.createQuery("from Pelanggan pelanggan where pelanggan.nama Like ? order by pelanggan.id asc").setParameter(0, "%"+textKataPencarian.getText()+"%").list();
            tabelPelanggan.setModel (new PelangganTableModel(pelanggans));
        }catch(HibernateException e){
            e.printStackTrace();
        }
    }
    
    public Pelanggan getPelanggan(){
        return pelanggan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textKataPencarian = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        buttonKelolaData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DAFTAR PELANGGAN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Masukkan Nama Pelanggan");

        textKataPencarian.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonCari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buttonCari.setText("CARI");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        tabelPelanggan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPelanggan);

        buttonKelolaData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buttonKelolaData.setText("KELOLAH DATA");
        buttonKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelolaDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textKataPencarian)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCari))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonKelolaData)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textKataPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buttonKelolaData)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelolaDataActionPerformed
        // TODO add your handling code here:
        int row = tabelPelanggan.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(rootPane, "Pilih data pada tabel!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String idPelanggan = tabelPelanggan.getValueAt(row, 0).toString();
        try{
            session = SESSION_FACTORY.openSession();
            session.beginTransaction();
            pelanggan = (Pelanggan) session.createQuery("from Pelanggan p where p.id=?").setParameter(0, idPelanggan).uniqueResult();
        }catch(HibernateException he){
            session.getTransaction().rollback();
        }
        session.close();
        FormPelanggan fromPelanggan = new FormPelanggan(null, true);
        fromPelanggan.setComponent(pelanggan);
        this.dispose();
        fromPelanggan.show();
    }//GEN-LAST:event_buttonKelolaDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListPelanggan dialog = new ListPelanggan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonKelolaData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTextField textKataPencarian;
    // End of variables declaration//GEN-END:variables
}
